pipeline {
  agent {
    node {
      label 'docker-build-node'
    }
  }
  
  options {
    timestamps()
  }

  environment {
        DOCKER_REGISTRY = "249767383774.dkr.ecr.ap-southeast-1.amazonaws.com"
        CREDENTIAL_ID = "ecr:ap-southeast-1:jenkins-ecr"
        IMAGE = "xpx-catapult-faucet"
    }

  stages {
    stage('Build and Publish Release Image'){
      steps {
        echo 'Build and Publish Image'
        script {
          def newImage = docker.build("${IMAGE}")
          docker.withRegistry("https://${DOCKER_REGISTRY}", "${CREDENTIAL_ID}"){
            newImage.push("master-jenkins-build-${env.BUILD_NUMBER}") // push using Jenkins build number
            newImage.push("master") //update Docker Image master
          }
        }
      }
      post {
        success {
          slackSend channel: '#devops',
            color: 'good',
            message: "Branch *${env.GIT_BRANCH}* build of *${currentBuild.fullDisplayName}* completed successfully :100:\nPushed Docker image ${DOCKER_REGISTRY}/${IMAGE}:${env.GIT_BRANCH}"
        }
      }
    }
  }

  post {
    failure {
      slackSend channel: '#devops',
        color: 'bad',
        message: "Branch *${env.GIT_BRANCH}* of *${currentBuild.fullDisplayName}* FAILED :scream:"
    }
  }
}