pipeline {
  agent {
    node {
      label 'docker-build-node'
    }
  }
  
  options {
    timestamps()
  }

  environment {
        DOCKER_REGISTRY = "249767383774.dkr.ecr.ap-southeast-1.amazonaws.com"
        CREDENTIAL_ID = "ecr:ap-southeast-1:jenkins-ecr"
        IMAGE = "xpx-catapult-faucet"
    }

  stages {
    stage('Build'){
      steps {
        withDockerContainer(image: 'golang:1.14.6-buster', args:'-u root') {
          sh '''
          export GO111MODULE=on && \
            go mod download && \
            go mod vendor && \
            cd cmd && \
            CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -tags netgo -ldflags '-w' -o server.run
          '''
        }
                  
        withDockerContainer(image: 'node:10'){
          sh '''
            cd frontend
            npm install
            npm run build
          '''
        }
      }
    }

    stage('Archive Artifact'){
      steps{
        sh '''
          tar -Jcvf xpx-catapult-faucet.tar.xz server.run frontends/dist/
        '''
        archiveArtifacts 'xpx-catapult-faucet.tar.xz'
      }
    }

    stage('Publish Image'){
      when {
        tag "v*"
      }
      steps {
        script {
          def newImage = docker.build("${IMAGE}")
          docker.withRegistry("https://${DOCKER_REGISTRY}", "${CREDENTIAL_ID}"){
            newImage.push("${env.GIT_BRANCH}")
          }
        }
      }
      post {
        success {
          slackSend channel: '#devops',
            color: 'good',
            message: "Branch *${env.GIT_BRANCH}* build of *${currentBuild.fullDisplayName}* completed successfully :100:\nPushed Docker image ${DOCKER_REGISTRY}/${IMAGE}:${env.GIT_BRANCH}"
        }
      }
    }
  }

  post {
    failure {
      slackSend channel: '#devops',
        color: 'bad',
        message: "Branch *${env.GIT_BRANCH}* of *${currentBuild.fullDisplayName}* FAILED :scream:"
    }
  }
}